### ISSUE TITLE
BF2Stats

### ISSUE THREAD

**Issue by lJasonl** [BF2Statistics/ControlCenter#3]
Here's to hoping you see this... 
     First and foremost I cannot register an account on bf2stats.com.. i keep putting in my PID # but it won't take it. (yes from battlelog.co). More importantly I cannot seem to get bf2 stats to work for me anymore. I get an error that says, "cannot load DLL SQLite.interop.dll The specific module could not be found (exception from HRESULT : 0x8007007E). This happens when I click the Start ASP button. This worked fine on my old comp but I had to get a new one. Please help me.
-Jason
![untitled](https://cloud.githubusercontent.com/assets/11781138/6978318/44607f8c-d99e-11e4-9415-071310580aa7.jpg)

**Comment by wilson212** [comment]
Well first off, thank you for including the screenshot. I was un-aware that the banner does that on higher DPI settings like that. Which version of the control center are you using? One of my previous releases was missing the DLL from the installer. If you open your Control Center program folder, does the SQLite.Interop.dll file exist?

**Comment by lJasonl** [comment]
Thanks for getting back with me. I have version 2.0.1... I'm aware of 2.0.2 and tried it but with the same result. That particular .dll is in the CC folder as well. Also thanks for the PID fix.

**Comment by wilson212** [comment]
Try creating a folder in your program folder there called "x86" and place the SQLite.Interop.dll inside that folder. Its possible this might fix it

**Comment by lJasonl** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/11781138/6991067/34ca1e06-da4e-11e4-9a34-bac8c8f289b3.jpg)
Do you mean like this? I didn't seem to work.

**Comment by lJasonl** [comment]
I have .Net Framework 4.5.2. Does that make a difference?

**Comment by wilson212** [comment]
Ensure that you have this installed as well

http://www.microsoft.com/en-us/download/details.aspx?id=30679

It should have installed automatically, but if the Control Center is running (as seen in the pics), then having 4.5.2 shouldnt matter, though you could also install 4.5 and see if that fixes things?

**Comment by lJasonl** [comment]
The C++ seemed to be what I needed. It's fixed thank you very much.

**Comment by wilson212** [comment]
I'm glad that fixed it for you... The installer should have installed that automatically if you were missing it, but apparently its not working as intended.
